version: "3.7"

services:
  nest-learning-pg:
    image: postgres:13
    container_name: nest-learning-pg
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=nest_learn
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5